import React from 'react'
import { Link } from 'react-router-dom'
import { colors, players } from '../assets'

const Home = () => {
  return (
    <>
      <section className="max-w-7xl h-screen mx-auto relative z-">
        <img src={players} className="absolute right-12 top-0 z-20 animate-[player_11s_ease-in-out_infinite]"></img>
        <img src={colors} className="absolute right-0 top-0 max-w-[800px] animate-pulse"></img>
        <div className="relative inset-y-32">
          <h1 className="font-extrabold font-mono text-[#222328] text-5xl">Soccer Cards Showcase</h1>
          <p className="mt-2 text-[#666e75] text-md max-w-[500px]">
            Browse through a collection of imaginative and visually stunning soccer player cards images generated by
            Midjourney AI
          </p>
          <div className="mt-8">
            <Link to="/create-post" className="font-inter font-medium bg-[#6469ff] text-white  p-2 rounded-md">
              Create a new player
            </Link>
            <Link to="/show-posts" className="font-inter font-medium bg-[#6469ff] text-white ml-6 p-2 rounded-md">
              Show players created
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}

export default Home
