import React from 'react'
import { Link } from 'react-router-dom'
import { colors, players } from '../assets'

const Home = () => {
  return (
    <>
      <section className="max-w-7xl mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <img src={players} className="object-cover w-full animate-[player_11s_ease-in-out_infinite]" />
          <div className="flex flex-col justify-center">
            <h1 className="font-extrabold font-mono text-[#222328] text-5xl mb-4 md:mb-6">Soccer Cards Showcase</h1>
            <p className="text-[#666e75] text-md max-w-md mb-8 md:mb-12">
              Browse through a collection of imaginative and visually stunning soccer player cards images generated by
              Midjourney AI
            </p>
            <div className="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-4">
              <Link to="/create-post" className="font-inter font-medium bg-[#6469ff] text-white py-2 px-4 rounded-md">
                Create a new player
              </Link>
              <Link to="/show-posts" className="font-inter font-medium bg-[#6469ff] text-white py-2 px-4 rounded-md">
                Show players created
              </Link>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default Home
